import { describe, it, expect, afterAll } from "vitest";
import { emitTypesDts } from "../src/compiler/emit/types-dts.js";
import type { SkillMeta } from "../src/types.js";
import { readFileSync, rmSync, mkdirSync, existsSync } from "node:fs";
import { join } from "node:path";
import { tmpdir } from "node:os";

const outputDir = join(tmpdir(), "review-skill-test-emit");

afterAll(() => rmSync(outputDir, { recursive: true, force: true }));

const sampleEntries: SkillMeta[] = [
  {
    path: "/",
    title: "Root Skill",
    description: "Root desc",
    isSkill: true,
    source: { characters: 1000, tokens: 250 },
    runtime: { characters: 800, tokens: 200 },
    files: 3,
  },
  {
    path: "/review",
    title: "Code Review",
    description: "Review rules",
    isSkill: true,
    source: { characters: 2000, tokens: 500 },
    runtime: { characters: 1600, tokens: 400 },
    files: 2,
  },
  {
    path: "/review/rules.md",
    title: "State Rules",
    description: "State management rules",
    isSkill: false,
    source: { characters: 1500, tokens: 375 },
    runtime: { characters: 1200, tokens: 300 },
  },
];

describe("emitTypesDts", () => {
  it("generates .skill/skill.ts", async () => {
    mkdirSync(outputDir, { recursive: true });
    await emitTypesDts(sampleEntries, outputDir, "en");
    const path = join(outputDir, "skill.ts");
    expect(existsSync(path)).toBe(true);
    const content = readFileSync(path, "utf-8");

    // Header
    expect(content).toContain("Generated by review-skill compiler");

    // Imports from review-skill
    expect(content).toContain('import { skill as _skill, loadMetadata } from "review-skill"');
    expect(content).toContain('export type { SkillRef, SkillMeta, SkillStats } from "review-skill"');

    // Metadata loading
    expect(content).toContain('const _meta = loadMetadata(".skill")');

    // Path types
    expect(content).toContain('export type SkillPath =');
    expect(content).toContain('| "/"');
    expect(content).toContain('| "/review"');
    expect(content).toContain('export type ResourcePath =');
    expect(content).toContain('| "/review/rules.md"');

    // Overloads
    expect(content).toContain('skill(path: "/"):');
    expect(content).toContain('skill(path: "/review"):');
    expect(content).toContain('skill(path: "/review/rules.md"):');

    // Runtime implementation
    expect(content).toContain("export function skill(path: string)");
    expect(content).toContain("return _skill(path)");

    // Fallback
    expect(content).toContain("Fallback");
  });

  it("generates Chinese labels when lang=zh-CN", async () => {
    await emitTypesDts(sampleEntries, outputDir, "zh-CN");
    const content = readFileSync(join(outputDir, "skill.ts"), "utf-8");
    expect(content).toContain("当前文件");
    expect(content).toContain("预计编译后");
    expect(content).toContain("字符数");
    expect(content).toContain("Token");
  });

  it("generates English labels when lang=en", async () => {
    await emitTypesDts(sampleEntries, outputDir, "en");
    const content = readFileSync(join(outputDir, "skill.ts"), "utf-8");
    expect(content).toContain("Current file");
    expect(content).toContain("Estimated after build");
    expect(content).toContain("Chars");
    expect(content).toContain("Tokens");
  });

  it("generates JSDoc with hover info", async () => {
    await emitTypesDts(sampleEntries, outputDir, "en");
    const content = readFileSync(join(outputDir, "skill.ts"), "utf-8");

    // Title in JSDoc
    expect(content).toContain("**Code Review**");
    expect(content).toContain("**State Rules**");

    // Source file path
    expect(content).toContain("skills/SKILL.md");
    expect(content).toContain("skills/review/SKILL.md");
    expect(content).toContain("skills/review/rules.md");

    // Token stats
    expect(content).toContain("Tokens");
    expect(content).toContain("~400");
  });

  it("handles empty entries", async () => {
    await emitTypesDts([], outputDir, "en");
    const content = readFileSync(join(outputDir, "skill.ts"), "utf-8");
    expect(content).toContain("SkillPath =");
    expect(content).toContain("ResourcePath =");
    expect(content).toContain("never;");
  });

  it("handles root-only entries", async () => {
    const entries: SkillMeta[] = [{
      path: "/",
      title: "Root",
      description: "",
      isSkill: true,
      source: { characters: 100, tokens: 25 },
      runtime: { characters: 80, tokens: 20 },
    }];
    await emitTypesDts(entries, outputDir, "en");
    const content = readFileSync(join(outputDir, "skill.ts"), "utf-8");
    expect(content).toContain('| "/"');
    expect(content).toContain('skill(path: "/"):');
  });
});
