import { writeFile, mkdir } from "node:fs/promises";
import { join } from "node:path";
import type { SkillMeta } from "../../types.js";

const LABELS: Record<string, Record<string, string>> = {
  en: {
    sourceTitle: "── Current file ──",
    runtimeTitle: "── Estimated after build ──",
    files: "Files",
    characters: "Chars",
    tokens: "Tokens",
  },
  "zh-CN": {
    sourceTitle: "── 当前文件 ──",
    runtimeTitle: "── 预计编译后 ──",
    files: "文件数",
    characters: "字符数",
    tokens: "Token",
  },
};

/**
 * Generate `.skill/skill.ts` — a wrapper module that adds typed overloads
 * to skill() with JSDoc hover info.
 */
export async function emitTypesDts(
  entries: SkillMeta[],
  outputDir: string,
  lang: string = "en"
): Promise<void> {
  const L = LABELS[lang] ?? LABELS.en;
  const labelW = 10;
  const skills = entries.filter((e) => e.isSkill);
  const resources = entries.filter((e) => !e.isSkill);

  const sorted = [...entries].sort((a, b) => {
    if (a.path === "/") return -1;
    if (b.path === "/") return 1;
    return a.path.length - b.path.length || a.path.localeCompare(b.path);
  });

  function formatUnion(items: string[]): string[] {
    if (items.length === 0) return ["  never;"];
    return items.map((item, i) => {
      const suffix = i === items.length - 1 ? ";" : "";
      return `  | ${item}${suffix}`;
    });
  }

  function jsDoc(entry: SkillMeta): string {
    const kind = entry.isSkill ? "Skill" : "Resource";

    function pad(label: string, n: number): string {
      return label.padEnd(n);
    }

    const sourceFile = entry.isSkill
      ? `skills/${entry.path === "/" ? "" : entry.path.replace(/^\//, "")}/SKILL.md`.replace(/\/$/, "/SKILL.md").replace(/\/\//g, "/")
      : `skills/${entry.path.replace(/^\//, "")}`;

    const lines: string[] = ["/**"];

    lines.push(` * **${entry.title || entry.path}**`);
    if (entry.description) {
      lines.push(` *`);
      lines.push(` * ${entry.description}`);
    }
    lines.push(` *`);
    lines.push(` * \`skill(${JSON.stringify(entry.path)})\`  →  ${kind}`);
    lines.push(` *`);
    lines.push(` * 📄 ${sourceFile}`);
    lines.push(` *`);
    const sc = entry.source.characters;
    const rc = entry.runtime.characters;
    const sr = entry.source.tokens;
    const rt = entry.runtime.tokens;
    const cpct = sc > 0 ? ((1 - rc / sc) * 100).toFixed(1) : "0.0";
    const tpct = sr > 0 ? ((1 - rt / sr) * 100).toFixed(1) : "0.0";

    lines.push(` *`);
    lines.push(` * ${L.sourceTitle}`);
    if (entry.isSkill && entry.files) {
      lines.push(` *   ${pad(L.files, labelW - 2)} ${entry.files.toLocaleString()}`);
    }
    lines.push(` *   ${pad(L.characters, labelW - 2)} ${sc.toLocaleString()}`);
    lines.push(` *   ${pad(L.tokens, labelW - 2)} ~${sr.toLocaleString()}`);
    lines.push(` *`);
    lines.push(` * ${L.runtimeTitle}`);
    lines.push(` *   ${pad(L.characters, labelW - 2)} ${rc.toLocaleString()}  \`↓${cpct}%\``);
    lines.push(` *   ${pad(L.tokens, labelW - 2)} ~${rt.toLocaleString()}  \`↓${tpct}%\``);
    lines.push(" */");
    return lines.join("\n");
  }

  const lines: string[] = [
    "// Generated by review-skill compiler. DO NOT EDIT.",
    "",
    "/* eslint-disable */",
    "",
    'import { skill as _skill, loadMetadata } from "review-skill";',
    'export type { SkillRef, SkillMeta, SkillStats } from "review-skill";',
    "",
    'const _meta = loadMetadata(".skill");',
    "",
    "export type SkillPath =",
    ...formatUnion(skills.map((s) => JSON.stringify(s.path))),
    "",
    "export type ResourcePath =",
    ...formatUnion(resources.map((s) => JSON.stringify(s.path))),
    "",
    "export type SkillAddress = SkillPath | ResourcePath;",
    "",
  ];

  for (const entry of sorted) {
    lines.push(jsDoc(entry));
    lines.push(
      `export function skill(path: ${JSON.stringify(entry.path)}): import("review-skill").SkillRef;`
    );
    lines.push("");
  }

  lines.push("/** Fallback — unknown path */");
  lines.push('export function skill(path: string): import("review-skill").SkillRef;');
  lines.push("");

  // Runtime implementation — delegates to review-skill
  lines.push("export function skill(path: string): import(\"review-skill\").SkillRef {");
  lines.push('  return _skill(path);');
  lines.push("}");
  lines.push("");

  await mkdir(outputDir, { recursive: true });
  await writeFile(join(outputDir, "skill.ts"), lines.join("\n"), "utf-8");
}
