import { writeFile, mkdir } from "node:fs/promises";
import { join } from "node:path";
import type { SkillMeta } from "../../types.js";

const LABELS: Record<string, Record<string, string>> = {
  en: {
    sourceTitle: "── Source ──",
    files: "Files",
    characters: "Chars",
    tokens: "Tokens",
    runtimeTitle: "── Runtime ──",
    core: "Core",
    typical: "Typical",
    p95: "P95",
    max: "Max",
  },
  "zh-CN": {
    sourceTitle: "── 编译前 ──",
    files: "文件数",
    characters: "字符数",
    tokens: "Token",
    runtimeTitle: "── 编译后 ──",
    core: "核心",
    typical: "常用",
    p95: "P95",
    max: "最大",
  },
};

export async function emitTypesDts(
  entries: SkillMeta[],
  outputDir: string,
  lang: string = "en"
): Promise<void> {
  const L = LABELS[lang] ?? LABELS.en;
  const labelW = 10;
  const skills = entries.filter((e) => e.isSkill);
  const resources = entries.filter((e) => !e.isSkill);

  const sorted = [...entries].sort((a, b) => {
    if (a.path === "/") return -1;
    if (b.path === "/") return 1;
    return a.path.length - b.path.length || a.path.localeCompare(b.path);
  });

  function formatUnion(items: string[]): string[] {
    if (items.length === 0) return ["  never;"];
    return items.map((item, i) => {
      const suffix = i === items.length - 1 ? ";" : "";
      return `  | ${item}${suffix}`;
    });
  }

  function jsDoc(entry: SkillMeta): string {
    const kind = entry.isSkill ? "Skill" : "Resource";

    function pad(label: string, n: number): string {
      return label.padEnd(n);
    }

    // Resolve the actual filesystem path for the hint line
    const sourceFile = entry.isSkill
      ? `skills/${entry.path === "/" ? "" : entry.path.replace(/^\//, "")}/SKILL.md`.replace(/\/$/, "/SKILL.md").replace(/\/\//g, "/")
      : `skills/${entry.path.replace(/^\//, "")}`;

    const lines: string[] = ["/**"];

    // Title + description
    lines.push(` * **${entry.title || entry.path}**`);
    if (entry.description) {
      lines.push(` *`);
      lines.push(` * ${entry.description}`);
    }

    // Signature + source file
    lines.push(` *`);
    lines.push(` * \`skill(${JSON.stringify(entry.path)})\`  →  ${kind}`);
    lines.push(` *`);
    lines.push(` * 📄 ${sourceFile}`);

    // ── Source block ──
    lines.push(` *`);
    lines.push(` * ${L.sourceTitle}`);
    if (entry.isSkill && entry.files) {
      lines.push(` * - ${pad(L.files, labelW - 2)} ${entry.files.toLocaleString()}`);
    }
    lines.push(` * - ${pad(L.characters, labelW - 2)} ${entry.source.characters.toLocaleString()}`);
    lines.push(` * - ${pad(L.tokens, labelW - 2)} ~${entry.source.tokens.toLocaleString()}`);

    // ── Runtime block ──
    lines.push(` *`);
    lines.push(` * ${L.runtimeTitle}`);
    if (entry.isSkill && entry.typical) {
      lines.push(` * - ${pad(L.core, labelW - 2)} ~${entry.runtime.tokens.toLocaleString()}`);
      lines.push(` * - ${pad(L.typical, labelW - 2)} ~${entry.typical.toLocaleString()}`);
      if (entry.p95) lines.push(` * - ${pad(L.p95, labelW - 2)} ~${entry.p95.toLocaleString()}`);
      if (entry.max) lines.push(` * - ${pad(L.max, labelW - 2)} ~${entry.max.toLocaleString()}`);
    } else {
      lines.push(` * - ${pad(L.characters, labelW - 2)} ${entry.runtime.characters.toLocaleString()}`);
      lines.push(` * - ${pad(L.tokens, labelW - 2)} ~${entry.runtime.tokens.toLocaleString()}`);
    }

    lines.push(" */");
    return lines.join("\n");
  }

  const lines: string[] = [
    "// Generated by review compiler. DO NOT EDIT.",
    "",
    "/* eslint-disable */",
    "",
    'import { resolveSkill, loadMetadata } from "review-skill";',
    'import type { SkillRef, SkillMeta, SkillStats } from "review-skill";',
    'export type { SkillRef, SkillMeta, SkillStats };',
    "",
    "// Metadata loaded once at import time — skill() is synchronous.",
    'const _meta = loadMetadata(".skill");',
    "",
    "// ── Path types ────────────────────────────────────────────",
    "",
    "export type SkillPath =",
    ...formatUnion(skills.map((s) => JSON.stringify(s.path))),
    "",
    "export type ResourcePath =",
    ...formatUnion(resources.map((s) => JSON.stringify(s.path))),
    "",
    "export type SkillAddress = SkillPath | ResourcePath;",
    "",
    "// ── Typed overloads (sync — no await needed) ───────────────",
    "",
  ];

  for (const entry of sorted) {
    lines.push(jsDoc(entry));
    lines.push(
      `export function skill(path: ${JSON.stringify(entry.path)}): SkillRef;`
    );
    lines.push("");
  }

  lines.push("/** Fallback — unknown path */");
  lines.push("export function skill(path: string): SkillRef;");
  lines.push("");

  // ── Runtime implementation ─
  lines.push('export function skill(path: string): SkillRef {');
  lines.push('  return resolveSkill(path, _meta, ".skill");');
  lines.push("}");
  lines.push("");

  await mkdir(outputDir, { recursive: true });
  await writeFile(join(outputDir, "skill.ts"), lines.join("\n"), "utf-8");
}
