import { writeFile, mkdir } from "node:fs/promises";
import { join } from "node:path";
import type { SkillMeta } from "../../types.js";

const LABELS: Record<string, Record<string, string>> = {
  en: {
    sourceTitle: "── Source ──",
    files: "Files",
    characters: "Chars",
    tokens: "Tokens",
    runtimeTitle: "── Runtime ──",
    core: "Core",
    typical: "Typical",
    p95: "P95",
    max: "Max",
  },
  "zh-CN": {
    sourceTitle: "── 编译前 ──",
    files: "文件数",
    characters: "字符数",
    tokens: "Token",
    runtimeTitle: "── 编译后 ──",
    core: "核心",
    typical: "常用",
    p95: "P95",
    max: "最大",
  },
};

/**
 * Generate `.skill/types.d.ts` — module augmentation that adds
 * typed overloads to `review-skill`'s `skill()` function.
 *
 * Users only need ONE import: `import { skill } from "review-skill"`
 * TypeScript picks up the augmentation via tsconfig `include: [".skill"]`
 */
export async function emitTypesDts(
  entries: SkillMeta[],
  outputDir: string,
  lang: string = "en"
): Promise<void> {
  const L = LABELS[lang] ?? LABELS.en;
  const labelW = 10;
  const skills = entries.filter((e) => e.isSkill);
  const resources = entries.filter((e) => !e.isSkill);

  const sorted = [...entries].sort((a, b) => {
    if (a.path === "/") return -1;
    if (b.path === "/") return 1;
    return a.path.length - b.path.length || a.path.localeCompare(b.path);
  });

  function formatUnion(items: string[]): string[] {
    if (items.length === 0) return ["  never;"];
    return items.map((item, i) => {
      const suffix = i === items.length - 1 ? ";" : "";
      return `  | ${item}${suffix}`;
    });
  }

  function jsDoc(entry: SkillMeta): string {
    const kind = entry.isSkill ? "Skill" : "Resource";

    function pad(label: string, n: number): string {
      return label.padEnd(n);
    }

    const sourceFile = entry.isSkill
      ? `skills/${entry.path === "/" ? "" : entry.path.replace(/^\//, "")}/SKILL.md`.replace(/\/$/, "/SKILL.md").replace(/\/\//g, "/")
      : `skills/${entry.path.replace(/^\//, "")}`;

    const lines: string[] = ["  /**"];

    lines.push(`   * **${entry.title || entry.path}**`);
    if (entry.description) {
      lines.push(`   *`);
      lines.push(`   * ${entry.description}`);
    }
    lines.push(`   *`);
    lines.push(`   * \`skill(${JSON.stringify(entry.path)})\`  →  ${kind}`);
    lines.push(`   *`);
    lines.push(`   * 📄 ${sourceFile}`);
    lines.push(`   *`);
    lines.push(`   * ${L.sourceTitle}`);
    if (entry.isSkill && entry.files) {
      lines.push(`   * - ${pad(L.files, labelW - 2)} ${entry.files.toLocaleString()}`);
    }
    lines.push(`   * - ${pad(L.characters, labelW - 2)} ${entry.source.characters.toLocaleString()}`);
    lines.push(`   * - ${pad(L.tokens, labelW - 2)} ~${entry.source.tokens.toLocaleString()}`);
    lines.push(`   *`);
    lines.push(`   * ${L.runtimeTitle}`);
    if (entry.isSkill && entry.typical) {
      lines.push(`   * - ${pad(L.core, labelW - 2)} ~${entry.runtime.tokens.toLocaleString()}`);
      lines.push(`   * - ${pad(L.typical, labelW - 2)} ~${entry.typical.toLocaleString()}`);
      if (entry.p95) lines.push(`   * - ${pad(L.p95, labelW - 2)} ~${entry.p95.toLocaleString()}`);
      if (entry.max) lines.push(`   * - ${pad(L.max, labelW - 2)} ~${entry.max.toLocaleString()}`);
    } else {
      lines.push(`   * - ${pad(L.characters, labelW - 2)} ${entry.runtime.characters.toLocaleString()}`);
      lines.push(`   * - ${pad(L.tokens, labelW - 2)} ~${entry.runtime.tokens.toLocaleString()}`);
    }
    lines.push("   */");
    return lines.join("\n");
  }

  const lines: string[] = [
    "// Generated by review-skill compiler. DO NOT EDIT.",
    "",
    "/* eslint-disable */",
    "",
    "export type SkillPath =",
    ...formatUnion(skills.map((s) => JSON.stringify(s.path))),
    "",
    "export type ResourcePath =",
    ...formatUnion(resources.map((s) => JSON.stringify(s.path))),
    "",
    "export type SkillAddress = SkillPath | ResourcePath;",
    "",
    "declare module \"review-skill\" {",
    "  import type { SkillRef } from \"review-skill\";",
    "",
  ];

  for (const entry of sorted) {
    lines.push(jsDoc(entry));
    lines.push(
      `  export function skill(path: ${JSON.stringify(entry.path)}): SkillRef;`
    );
    lines.push("");
  }

  lines.push("}");
  lines.push("");

  await mkdir(outputDir, { recursive: true });
  await writeFile(join(outputDir, "types.d.ts"), lines.join("\n"), "utf-8");
}
